### ISSUE TITLE
when run smc 100 times it caused problem

### ISSUE THREAD

**Issue by JohannGoethe** [elfi-dev/elfi#257] opened 2018-04-02 06:52 UTC
#### Summary:
Please provide a short couple sentence summary.

I am doing smc ABC using elfi smc as instructed on the official website tutoirial

#### Description:
Describe the issue as clearly as possible.

if I run once, there is no problem, but if I want to infer the parameter 100 times using a for loop, it caused problem, I can't run it, when I run the first of the loops, it's ok, and takes about 20s, the second, it becomes 1 minute, and third, it always said there is not enough examples....and elfi is trying.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

below is the code, while Ms is just the function which you could ignore. S1 is the summary statistics.

def Ms(alpha, beta, batch_size=1, random_state=None):
    y = [1]
    alpha = np.float(alpha)
    beta = np.float(beta)
    theta = [alpha, alpha*beta, tao]
    theta = theta/np.sum(theta)
#    theta = map(float, theta)
    i = 1 
    while i < 20:
        if y == []:
            break
        else:
            b = np.random.multinomial(1, theta, size=1)
            i = i + 1
            if b[0][2] == 1:
                y = y + [1]
            elif b[0][0] == 1:
                q = y/np.sum(y)
                p = q.tolist()
                a = np.random.multinomial(1, p, size=1).tolist()[0]
                y = [f+g for f,g in zip(y,a)]
            else:
                i = i - 2
                q = y/np.sum(y)
                p = q.tolist()
                a = np.random.multinomial(1, p, size=1).tolist()[0]
                y = [f-g for f,g in zip(y,a)]
                while 0 in y:
                    y.remove(0)
        yalpha = sorted(y)
    return yalpha

def S1(x):
    t1 = len(x)/20
    return t1

start=time.time()
for i in range(100):
    np.random.seed(seed+10000)
    alpha0s = np.random.uniform(0.05,2,size=1)
    beta0s = np.random.uniform(0.05,0.2,size=1)
    y0s = Ms(alpha0s, beta0s)
    
    alpha = elfi.Prior(scipy.stats.uniform, 0.005, 2)
    beta = elfi.Prior(scipy.stats.uniform, 0.005, 0.2)
   
    Ys = elfi.Simulator(Ms, alpha, beta, observed=y0s)
    Sus1 = elfi.Summary(S1, Ys)    
 
    ds1 = elfi.Distance('euclidean', Sus1)
    smc = elfi.SMC(ds1, batch_size=1, seed=seed)
        
    N = 1000
    schedule = [0.7, 0.4, 0.05]
    %time result_smc = smc.sample(N, schedule)
    MSE1s = MSE1s + [np.square(result_smc.sample_means['alpha'] - alpha0s)]
    MSE2s = MSE2s + [np.square(result_smc.sample_means['beta'] - beta0s)]
end = time.time()
print(end-start)
print(np.mean(MSE1s)) 
print(np.mean(MSE2s))

#### Current Output:
The current output. Knowing what is the current behavior is useful.

if I run once, there is no problem, but if I want to infer the parameter 100 times using a for loop, it caused problem, I can't run it, when I run the first of the loops, it's ok, and takes about 20s, the second, it becomes 1 minute, and third, it always said there is not enough examples....and elfi is trying.

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

I want to get all the result like the first of the loop.

**Comment by lintusj1** [comment] 2018-04-03 07:03
Thanks for the report. It is a bit difficult to read the code but here are few observations. In each loop you should create a new model with `elfi.new_model()` before assigning new nodes. Otherwise the loop keeps adding new nodes to the same model that may cause slowing down of computation if all of them are being evaluated. Can you check what the model looks like after 2 iterations?

Not related to the problem, but inside your simulator you should use the `random_state` argument to create random numbers instead of `np.random`, i.e. `random_state.multinomial(...`. That way you will be able to get reproducible results and seeding is also properly handled in parallel computation.

Also it seems that you are producing the same observed data in every iteration since `np.random.seed(seed+10000)` produces the same seed every time unless the `seed` variable is somewhere changed (didn't notice it would).

**Comment by vuolleko** [comment] 2018-04-03 07:27
Also, the output from simulator `Ms` is confusing to ELFI, which expects the first dimension to match the `batch_size`. Since you're not taking advantage of vectorization, you could use `elfi.tools.vectorize`. Likewise, the dimensionality from `S1` should be fixed.

We are in the process of improving our documentation on vectorization.

**Comment by vuolleko** [comment] 2018-04-03 10:25
As a matter of fact I just added some explanation in #259. Could you read it and let me know if it clarifies my above comment? :)

**Comment by JohannGoethe** [comment] 2018-04-03 11:20
Many thanks to your help, it is very clear. I can't wait to edit my code and re-run it.

**Comment by vuolleko** [comment] 2018-04-10 06:55
Continues in #260

**Closed by vuolleko** 2018-04-10 06:55 UTC
